### ISSUE TITLE
Using applyRule with Double data types

### ISSUE THREAD

**Issue by chamitha** [advantagefse/json-logic-swift#15]
Hello. I'm applying JsonLogic to a Swift `Double` data type and expecting the result to be of the same type. 
```
{"if": [ {">": [ {"var": "double1"}, {"var": "double2"} ] }, {"var": "double1"} ]}
```
with the values
```
 { "double1":1618495500, "double2":1618495000 } 
```
My exception is for `JsonLogic.applyRule` to return a `Double` data type with the value 1618495500.
However given the `jsonDataOrNil` param of `applyRule` is a `String` data type I suspect the `Double` values are cast as `Int` as there is no explicit tag to denote these values as `Double`. Therefore `applyRule` returns an `Int` data type with the value 1618495500.
Note that if I adjust my values to include a fractional component `applyRule` returns a `Double` data type as expected.
```
 { "double1":1618495500.01, "double2":1618495000.01 } 
```
Keen to hear your thoughts on this and preferred workaround?

**Comment by csknns** [comment]
> My exception is for JsonLogic.applyRule to return a Double data type with the value 1618495500.

I understand your expectation but we can not know that 1618495500 is double. JSON has only one type for numbers and does not allow you to make any distinction between Integers and Floating points. This is a JSON limitation. So when you have a JSON the only way to declare that an number is of floating point type is to have decimal points. 
Because Swift makes a distinction between floating point & integer types when we need to interpret if a JSON number is double or int, we decide that by checking if it has a fractional component, since 1618495500 & 1618495000 do not have it they are interpreted as Integers.

JsonLogic will try to cast the result of the computation to the variable type you are trying to store the result
`let result: Int = try! applyRule(rule, to: data)`
 But swift does not allow casting between Int<->Double. However in the future I could improve a little the JsonLogic library to handle this internally.

A solution could be to explicitly convert it to Double, or use NSNumber:
```        
let result: NSNumber = try! applyRule(rule, to: data)

result.doubleValue
result.intValue
```
OR
```       
let result: Int = try! applyRule(rule, to: data)
let resultAsDouble = Double(result)
```       

I hope that helps!

**Comment by chamitha** [comment]
@csknns That is what I suspected and it makes sense. Setting a fraction of .00 makes no effect but .01 does. I like your suggestion of using NSNumber which is a workaround that doesn't modify the value. 👍
